### ISSUE TITLE
Unable to use model trained from teachable machine 

### ISSUE THREAD

**Issue by LokieVikky** [rupakkarki27/object_detection#1]
App crashes when I try to use model downloaded from teachable machine.
Could you please make steps on how to use models from teachable machine?
After training our model in Teachable machine there are several options to download like floting point model, edgetpu model and quantized model under tensorflow lite ...... which one to use?

**Comment by LokieVikky** [comment]
This is the stack trace when i tried to open realtime screen

 Caused by: java.lang.IllegalArgumentException: Cannot copy from a TensorFlowLite tensor (Identity) with shape [1, 1] to a Java object with shape [1, 1, 4].
E/AndroidRuntime( 5115): 	at org.tensorflow.lite.Tensor.throwIfDstShapeIsIncompatible(Tensor.java:482)
E/AndroidRuntime( 5115): 	at org.tensorflow.lite.Tensor.copyTo(Tensor.java:252)
E/AndroidRuntime( 5115): 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:175)
E/AndroidRuntime( 5115): 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:360)
E/AndroidRuntime( 5115): 	at sq.flutter.tflite.TflitePlugin$RunSSDMobileNet.runTflite(TflitePlugin.java:651)
E/AndroidRuntime( 5115): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:448)
E/AndroidRuntime( 5115): 	at sq.flutter.tflite.TflitePlugin$TfliteTask.doInBackground(TflitePlugin.java:422)
E/AndroidRuntime( 5115): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/AndroidRuntime( 5115): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 5115): 	... 4 more
I/chatty  ( 5115): uid=10509(com.example.object_detection) FinalizerDaemon identical 1 line
W/System  ( 5115): A resource failed to call destroy. 
I/Process ( 5115): Sending signal. PID: 5115 SIG: 9

**Comment by rupakkarki27** [comment]
Download the model for TensorFlow lite with the model conversion type of Floating Point. The other steps should be similar to the one in here. 
For further reference read this article on medium:
https://heartbeat.fritz.ai/image-classification-on-mobile-with-flutter-tensorflow-lite-and-teachable-machine-f7de39598e0c

**Comment by LokieVikky** [comment]
I tried floating point model from teachable machine and still the same issue persists.
I even tried my custom model in your sample project and got the same error
Im using Tflite.detectObjectOnFrame for detection
